---
apiVersion: "v1"
kind: "List"
items:
- apiVersion: "v1"
  kind: "Service"
  metadata:
    labels:
      app: "station2"
      version: "1.0.0-SNAPSHOT"
      group: "edge-demo"
    name: "station2"
  spec:
    ports:
    - name: "http"
      port: 8080
      targetPort: 8080
    selector:
      app: "station2"
      version: "1.0.0-SNAPSHOT"
      group: "edge-demo"
    type: "ClusterIP"
- apiVersion: "apps/v1"
  kind: "Deployment"
  metadata:
    labels:
      app: "station2"
      version: "1.0.0-SNAPSHOT"
      group: "edge-demo"
    name: "station2"
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: "station2"
        version: "1.0.0-SNAPSHOT"
        group: "edge-demo"
    template:
      metadata:
        labels:
          app: "station2"
          version: "1.0.0-SNAPSHOT"
          group: "edge-demo"
      spec:
        containers:
        - env:
          - name: "KUBERNETES_NAMESPACE"
            valueFrom:
              fieldRef:
                fieldPath: "metadata.namespace"
          image: "edge-demo/station-service:1.0.0-SNAPSHOT"
          imagePullPolicy: "IfNotPresent"
          name: "station-service"
          ports:
          - containerPort: 8080
            name: "http"
            protocol: "TCP"
